import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { useEffect, useState } from 'react';
import { useRouter } from 'next/router';
import Paginador from '../components/Paginador';
import CartaJugador from '../components/CartaJugador';

import { obtenerJugadores } from '../lib/servicios/mir4';

export default function Home() {

  const [jugadores, setJugadores] = useState([]);
  const [page, setPage] = useState(1);
  const [limit, setLimit] = useState(10);
  const [hasPrevPage, setHasPrevPage] = useState(false);
  const [hasNextPage, setHasNextPage] = useState(true);

  const handleNextPage = () => {
    setPage(page + 1);
  }

  const handlePrevPage = () => {
    setPage(page - 1);
  }

  const handleRequestJugadores = async () => {
    obtenerJugadores({ page, limit })
      .then(({ jugadores, hasPrevPage, hasNextPage }) => {
        setJugadores(jugadores);
        setHasPrevPage(hasPrevPage);
        setHasNextPage(hasNextPage);
      });
  }

  const handleClickPaginador = (arrowLeft) => {
    arrowLeft ? handlePrevPage() : handleNextPage();
  }

  useEffect(() => {
    handleRequestJugadores();
  }, [page]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Latam ATR</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Paginador onClick={handleClickPaginador} hasPrevPage={hasPrevPage} hasNextPage={hasNextPage} />
      <main className={styles.main}>
        <div className={styles.grid}>
          {
            jugadores.map((jugador, index) => {
              return <CartaJugador jugador={jugador} index={index} key={`card-jugador-${index}`} />
            })
          }
        </div>
      </main >

      <footer className={styles.footer}>
        <a
          href="https://mir4global.com/"
          target="_blank"
          rel="noopener noreferrer"
          key="link-mi4"
        >
          <span className={styles.logo}>
            <Image src="/mir4icon.png" alt="Mir4 Logo" width={86} height={86} />
          </span>
        </a>
        <a
          href="https://discord.gg/zsUeYZWDrU"
          target="_blank"
          rel="noopener noreferrer"
          key="link-discord"
        >
          <span className={styles.logo}>
            <Image src="/discord.png" alt="Discord Logo" width={86} height={86} />
          </span>
        </a>
      </footer>
    </div >
  )
}
